plugins {
    id 'java'
    id 'edu.sc.seis.launch4j' version '4.0.0'
    alias libs.plugins.shadow
}

group = 'com.lx862'
version = properties.version

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io/' }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation libs.common.cli
    implementation libs.common.io
    implementation libs.bundles.flatlaf
    implementation libs.bundles.commonmark
    implementation libs.gson
    implementation libs.toml4j
    implementation libs.bundles.imageio.ext
    implementation libs.rsyntaxtextarea
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}

jar {
    enabled = false
    archiveFileName = "${rootProject.name}-v${rootProject.version}-nodep.jar"
    manifest {
        attributes(
            'Main-Class': 'com.lx862.pwgui.Main'
        )
    }
}

launch4j {
    mainClassName = 'com.lx862.pwgui.Main'
    icon = "${projectDir}/assets/pwgui_icon.ico"
    outfile = "${rootProject.name}-v${project.version}.exe"
    errTitle = "This program requires at least Java 17 to run"
    downloadUrl = "https://adoptium.net/"
    jreMinVersion = "17.0.0"
    fileDescription = "Lightweight GUI Wrapper around packwiz, a Minecraft modpack tool."
    copyright = "AmberFrost"
    jarTask = project.tasks.shadowJar
}

build {
    dependsOn(shadowJar)
}

processResources {
    inputs.property "name", rootProject.name
    inputs.property "version", rootProject.version
    inputs.property "author", rootProject.properties.author

    filesMatching("build.json") {
        expand(
            "name": inputs.properties.name,
            "version": inputs.properties.version,
            "author": inputs.properties.author
        )
    }
}

shadowJar {
    archiveFileName = "${rootProject.name}-v${rootProject.version}.jar"
}

test {
    useJUnitPlatform()
}