[versions]
shadow = "9.3.1"
flatlaf = "3.7"
toml4j = "0.7.2"
common-io = "2.21.0"
common-cli = "1.11.0"
imageio = "3.13.0"
gson = "2.13.2"
commonmark = "0.27.1"
rsyntaxtextarea = "3.6.1"
ztzip = "1.17"
slf4j = "2.0.17"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
flatlaf = { group = "com.formdev", name = "flatlaf", version.ref = "flatlaf" }
flatlaf-ij-themes = { group = "com.formdev", name = "flatlaf-intellij-themes", version.ref = "flatlaf" }
flatlaf-extras = { group = "com.formdev", name = "flatlaf-extras", version.ref = "flatlaf" }
toml4j = { group = "com.moandjiezana.toml", name = "toml4j", version.ref = "toml4j" }
common-io = { group = "commons-io", name = "commons-io", version.ref = "common-io" }
common-cli = { group = "commons-cli", name = "commons-cli", version.ref = "common-cli" }
imageio-bmp = { group = "com.twelvemonkeys.imageio", name = "imageio-bmp", version.ref = "imageio" }
imageio-webp = { group = "com.twelvemonkeys.imageio", name = "imageio-webp", version.ref = "imageio" }
commonmark = { group = "org.commonmark", name = "commonmark", version.ref = "commonmark" }
commonmark-ext-gfm-table = { group = "org.commonmark", name = "commonmark-ext-gfm-tables", version.ref = "commonmark" }
commonmark-ext-gfm-strikethrough = { group = "org.commonmark", name = "commonmark-ext-gfm-strikethrough", version.ref = "commonmark" }
rsyntaxtextarea = { group = "com.fifesoft", name = "rsyntaxtextarea", version.ref = "rsyntaxtextarea" }
ztzip = { group = "org.zeroturnaround", name = "zt-zip", version.ref = "ztzip" }
slf4j-noop = { group = "org.slf4j", name = "slf4j-nop", version.ref = "slf4j"}

[bundles]
commonmark = ["commonmark", "commonmark-ext-gfm-table", "commonmark-ext-gfm-strikethrough"]
flatlaf = ["flatlaf", "flatlaf-ij-themes", "flatlaf-extras"]
imageio-ext = ["imageio-bmp", "imageio-webp"]